[tox]
isolated_build = True
envlist = py38,py39,py310,py311,py312,py313,py314,ruff

[testenv]
deps = 
    pytest
    rich
commands =
    {envpython} -V
    {envpython} -m pytest tests/ -v

[testenv:ruff]
basepython = python3
deps = ruff
commands =
    ruff check speedtest.py
